# This workflow will install dependencies, create coverage tests and run Pytest Coverage Commentator
# For more information see: https://github.com/coroo/pytest-coverage-commentator
name: pytest-coverage-commentator
on:
  pull_request:
    branches: 
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Build coverage file
      run: |
        export APPLICATION_SETTINGS=config_test.py
        export FLASK_APP=app
        export FLASK_ENV=test
        pipenv run python db_create.py # Create db from scratch in sqllite each time for testing
        pipenv run python -m pytest --cache-clear --junitxml=report.xml --cov=project test/ > pytest-coverage.txt
        
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
